kinect_upload_fw: fix a -Wstrict-aliasing warning
kinect_upload_fw.c:87:2: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]

Use a union when there is the need to use the same memory for variables
of incompatible types (especially if they have different storage size).